'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

number = 4000000;

sum = 2;

def fib(sum, fibn_1 = 1, fibn_2 = 2):
	fibn = fibn_1 + fibn_2;
	if fibn <= number:
		if fibn % 2 == 0:
			sum = sum + fibn;
		fib(sum, fibn_2, fibn);
	else:
		print(fibn_2);
		print(sum);

fib(sum);
